services:
  db:
    build: ./postgres
    image: painel-postgres:latest
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: painel
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: painel_db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U painel -d painel_db']
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s

volumes:
  db-data:
    name: painel_postgres_data
